// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD00c-_QcCpxNDc0Ee4e1g0pu4G9AJTdmU',
    appId: '1:772076034210:web:8bcd6990dc3fc88d415ffb',
    messagingSenderId: '772076034210',
    projectId: 'myfluttertest-e8d97',
    authDomain: 'myfluttertest-e8d97.firebaseapp.com',
    storageBucket: 'myfluttertest-e8d97.appspot.com',
    measurementId: 'G-6Z9DH15YPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGe8hhnd79TMkcNuvaZB2AgxzsuI-U8sw',
    appId: '1:772076034210:android:574e7063e0900546415ffb',
    messagingSenderId: '772076034210',
    projectId: 'myfluttertest-e8d97',
    storageBucket: 'myfluttertest-e8d97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWdvop3ZmSp4CyQZqwZWVOTxPv8grPAeE',
    appId: '1:772076034210:ios:a9cdb7aeb2bc81f3415ffb',
    messagingSenderId: '772076034210',
    projectId: 'myfluttertest-e8d97',
    storageBucket: 'myfluttertest-e8d97.appspot.com',
    iosClientId: '772076034210-ngm93ojkv7a6cl5or89fllf4vdrmsr4s.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttertestapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWdvop3ZmSp4CyQZqwZWVOTxPv8grPAeE',
    appId: '1:772076034210:ios:80b787c231b0e5ee415ffb',
    messagingSenderId: '772076034210',
    projectId: 'myfluttertest-e8d97',
    storageBucket: 'myfluttertest-e8d97.appspot.com',
    iosClientId: '772076034210-ucqf3tmsu6s0miot3ns1cn2jd3hm93on.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttertestapp.RunnerTests',
  );
}
