// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ5voGbMqWTHMgQ97lJ57yxM5P_qbUVsY',
    appId: '1:864860752246:web:826cf82e05928871599257',
    messagingSenderId: '864860752246',
    projectId: 'app-fitness-test',
    authDomain: 'app-fitness-test.firebaseapp.com',
    databaseURL: 'https://app-fitness-test-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-fitness-test.appspot.com',
    measurementId: 'G-42NW4XMBKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQgoXxUqWp7A5WsTl7Q2k970KINnj4t_w',
    appId: '1:864860752246:android:7d7a1661a09d9510599257',
    messagingSenderId: '864860752246',
    projectId: 'app-fitness-test',
    databaseURL: 'https://app-fitness-test-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-fitness-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVAWNXeGWOtVNR4Hbr7a79nCNcw9-mGeg',
    appId: '1:864860752246:ios:b51f858c33be4d84599257',
    messagingSenderId: '864860752246',
    projectId: 'app-fitness-test',
    databaseURL: 'https://app-fitness-test-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-fitness-test.appspot.com',
    iosBundleId: 'com.example.appFitnessTest2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVAWNXeGWOtVNR4Hbr7a79nCNcw9-mGeg',
    appId: '1:864860752246:ios:b51f858c33be4d84599257',
    messagingSenderId: '864860752246',
    projectId: 'app-fitness-test',
    databaseURL: 'https://app-fitness-test-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-fitness-test.appspot.com',
    iosBundleId: 'com.example.appFitnessTest2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ5voGbMqWTHMgQ97lJ57yxM5P_qbUVsY',
    appId: '1:864860752246:web:84d5401a81e43cb1599257',
    messagingSenderId: '864860752246',
    projectId: 'app-fitness-test',
    authDomain: 'app-fitness-test.firebaseapp.com',
    databaseURL: 'https://app-fitness-test-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-fitness-test.appspot.com',
    measurementId: 'G-L4GJJC8H84',
  );
}
